<?php
	echo "		
	<nav>
		<ul>
		<li><h3>Sales</h3></li>
		<li><a href ="AddSales.html" title="Add sales record" id="nav">Add</a></li>
		<li><a href ="DeleteSales.html" title="Delete sales record" id="nav">Delete</a></li>
		<li><a href ="EditSales.html" title="Edit sales record" id="nav">Edit</a></li>
		<li><a href ="ViewSales.html" title="View sale records" id="nav">View</a></li>
		<li><h3>Inventory</h3></li>
		<li><a href ="AddInventory.html" title="Add inventory record" id="nav">Add</a></li>
		<li><a href ="DeleteInventory.html" title="Delete inventory record" id="nav">Delete</a></li>
		<li><a href ="EditInventory.html" title="Edit inventory record" id="nav">Edit</a></li>
		<li><a href ="ViewInventory.html" title="View inventory records" id="nav">View</a></li>
		
		</ul>
		</nav>";
?>