<?php
	echo "		
	<nav>
		<ul>
		<li><h3>Sales</h3></li>
		<li><a href ="add_sales.php" title="Add sales record" id="nav">Add</a></li>
		<li><a href ="delete_sales.php" title="Delete sales record" id="nav">Delete</a></li>
		<li><a href ="edit_sales.php" title="Edit sales record" id="nav">Edit</a></li>
		<li><a href ="view_sales.php" title="View sale records" id="nav">View</a></li>
		<li><h3>Inventory</h3></li>
		<li><a href ="add_inventory.php" title="Add inventory record" id="nav">Add</a></li>
		<li><a href ="delete_inventory.php" title="Delete inventory record" id="nav">Delete</a></li>
		<li><a href ="edit_inventory.php" title="Edit inventory record" id="nav">Edit</a></li>
		<li><a href ="show_inventory.php" title="View inventory records" id="nav">View</a></li>
		
		</ul>
		</nav>";
?>