-- MySQL Script generated by MySQL Workbench
-- Thu Sep  6 17:49:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`SalesRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SalesRecord` (
  `No.` INT(3) NOT NULL AUTO_INCREMENT,
  `Product Name` VARCHAR(15) NOT NULL,
  `Quantity` INT(4) NOT NULL,
  `Price` INT(4) NOT NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`No.`),
  UNIQUE INDEX `No._UNIQUE` (`No.` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
