-- MySQL Script generated by MySQL Workbench
-- Thu Sep  6 18:22:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`SalesRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SalesRecord` (
  `No.` INT(3) NOT NULL AUTO_INCREMENT,
  `ProductName` VARCHAR(15) NOT NULL,
  `Quantity` INT(4) NOT NULL,
  `Price` INT(4) NOT NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`No.`),
  UNIQUE INDEX `No._UNIQUE` (`No.` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventory` (
  `ProductName` VARCHAR(15) NOT NULL,
  `Quantity` INT(4) NOT NULL,
  `Supplier` VARCHAR(20) NOT NULL,
  `Contact Number` INT(15) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Product Name`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
